run_logged $ARCHEOX_"INSTALL/packaging/base.sh
run_logged $ARCHEOX_"INSTALL/packaging/fonts.sh
run_logged $ARCHEOX_"INSTALL/packaging/nvim.sh
run_logged $ARCHEOX_"INSTALL/packaging/icons.sh
run_logged $ARCHEOX_"INSTALL/packaging/webapps.sh
run_logged $ARCHEOX_"INSTALL/packaging/tuis.sh
run_logged $ARCHEOX_"INSTALL/packaging/npx.sh
run_logged $ARCHEOX_"INSTALL/packaging/asus-rog.sh
run_logged $ARCHEOX_"INSTALL/packaging/framework16.sh
run_logged $ARCHEOX_"INSTALL/packaging/dell-xps-touchpad-haptics.sh
run_logged $ARCHEOX_"INSTALL/packaging/surface.sh
