name: Bulk Replace
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
           token: ${{ secrets.MY_PAT }}
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "ILV"
          replace: "ILV"
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-replace old names"
